### ISSUE TITLE
Is sqsh still alive and usable with ASE 16

### ISSUE THREAD

**Issue by neuffer** [vonloxley/sqsh#1]
Is sqsh still alive and usable with ASE 16?

**Comment by vonloxley** [comment]
Well, it's breathing but very shallowly. It should compile with ASE 16, at least Martins last work was making it compile with ASE 16. I can't test that as we are still on ASE 15.7 at work.

**Comment by robtoyota** [comment]
I know this is nearly a year old, but I can confirm that sqsh is working with ASE 16, at least for my querying needs. I was not involved in the setup though, so I don't know if anything had to be tweaked to get it working.

**Comment by vonloxley** [comment]
Thank you for the feedback!
