### ISSUE TITLE
Backport build fixes for new stable release?

### ISSUE THREAD

**Issue by epa** [vonloxley/sqsh#6]
Hi, I know there is a forked repository of sqsh with patches to build against recent FreeTDS versions: https://github.com/freddy77/sqsh/tree/freetds_compatibility

That fork works, but it's against the current master branch of sqsh, so it includes some changes for the upcoming 3.0 version of sqsh.  I would like to ask if you'll make a new 2.5.x stable release with build fixes.  I have backported the build fixes to apply against the 2.5.16 release (commit 2ee5d9be6a637d2269473a6e3a42eeee438e8214) so if you create a "stable" or "sqsh-2.5" branch I could send a merge request against that.

**Comment by vonloxley** [comment]
I created a branch [v2.5](https://github.com/vonloxley/sqsh/tree/v2.5). Do you want to create a pull request against it?

**Comment by epa** [comment]
https://github.com/vonloxley/sqsh/pull/7
